// Code generated by protoc-gen-micro
// source: document.proto
package pb

import (
	context "context"
	api "github.com/unistack-org/micro/v3/api"
	client "github.com/unistack-org/micro/v3/client"
)

func NewDocumentQRProcessingServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{
		&api.Endpoint{
			Name:    "DocumentQRProcessingService.GetDocumentQR",
			Path:    []string{"/document/{document_id}"},
			Method:  []string{"GET"},
			Handler: "rpc",
		},
		&api.Endpoint{
			Name:    "DocumentQRProcessingService.PostDocumentQR",
			Path:    []string{"/document/{document_id}"},
			Method:  []string{"POST"},
			Handler: "rpc",
		},
	}
}

type DocumentQRProcessingServiceClient interface {
	GetDocumentQR(ctx context.Context, req *PostQRRequest, opts ...client.CallOption) (*PostQRResponse, error)
	PostDocumentQR(ctx context.Context, req *PostQRRequest, opts ...client.CallOption) (*PostQRResponse, error)
}

type DocumentQRProcessingServiceServer interface {
	GetDocumentQR(ctx context.Context, req *PostQRRequest, rsp *PostQRResponse) error
	PostDocumentQR(ctx context.Context, req *PostQRRequest, rsp *PostQRResponse) error
}
