// Code generated by protoc-gen-micro
// source: metadata.proto
package pb

import (
	context "context"
	api "github.com/unistack-org/micro/v3/api"
	client "github.com/unistack-org/micro/v3/client"
)

func NewMetadataProcessingServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{
		&api.Endpoint{
			Name:    "MetadataProcessingService.GetFileMetadata",
			Path:    []string{"/metadata/{metadata_id}"},
			Method:  []string{"GET"},
			Handler: "rpc",
		},
		&api.Endpoint{
			Name:    "MetadataProcessingService.UpdateFileMetadata",
			Path:    []string{"/metadata/{update_metadata_id}"},
			Method:  []string{"PUT"},
			Body:    "*",
			Handler: "rpc",
		},
		&api.Endpoint{
			Name:    "MetadataProcessingService.FindAll",
			Path:    []string{"/metadata"},
			Method:  []string{"GET"},
			Stream:  true,
			Handler: "rpc",
		},
		&api.Endpoint{
			Name:    "MetadataProcessingService.FindAllWithConditions",
			Path:    []string{"/metadata/search"},
			Method:  []string{"POST"},
			Body:    "*",
			Stream:  true,
			Handler: "rpc",
		},
		&api.Endpoint{
			Name:    "MetadataProcessingService.FindAllWithTextSearching",
			Path:    []string{"/metadata/search/text"},
			Method:  []string{"POST"},
			Body:    "*",
			Stream:  true,
			Handler: "rpc",
		},
		&api.Endpoint{
			Name:    "MetadataProcessingService.FindAllWithFullSearching",
			Path:    []string{"/metadata/search/full"},
			Method:  []string{"POST"},
			Body:    "*",
			Stream:  true,
			Handler: "rpc",
		},
		&api.Endpoint{
			Name:    "MetadataProcessingService.SaveFingerprint",
			Path:    []string{"/metadata/fingerprint"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		&api.Endpoint{
			Name:    "MetadataProcessingService.FindAllFingerprintsByID",
			Path:    []string{"/metadata/files/{file_id}/fingerprints"},
			Method:  []string{"GET"},
			Handler: "rpc",
		},
	}
}

type MetadataProcessingServiceClient interface {
	GetFileMetadata(ctx context.Context, req *GetMetadataRequest, opts ...client.CallOption) (*GetMetadataResponse, error)
	UpdateFileMetadata(ctx context.Context, req *UpdateMetadataRequest, opts ...client.CallOption) (*UpdateMetadataResponse, error)
	FindAll(ctx context.Context, req *FindAllRequest, opts ...client.CallOption) (MetadataProcessingService_FindAllClient, error)
	FindAllWithConditions(ctx context.Context, req *FindAllWithConditionsRequest, opts ...client.CallOption) (MetadataProcessingService_FindAllWithConditionsClient, error)
	FindAllWithTextSearching(ctx context.Context, req *FindAllWithTextSearchingRequest, opts ...client.CallOption) (MetadataProcessingService_FindAllWithTextSearchingClient, error)
	FindAllWithFullSearching(ctx context.Context, req *FindAllWithTextSearchingRequest, opts ...client.CallOption) (MetadataProcessingService_FindAllWithFullSearchingClient, error)
	SaveFingerprint(ctx context.Context, req *SaveFingerprintRequest, opts ...client.CallOption) (*SaveFingerprintResponse, error)
	FindAllFingerprintsByID(ctx context.Context, req *FindAllFingerprintsByIDRequest, opts ...client.CallOption) (*FindAllFingerprintsByIDResponse, error)
}

type MetadataProcessingService_FindAllClient interface {
	Context() context.Context
	SendMsg(msg interface{}) error
	RecvMsg(msg interface{}) error
	Close() error
	Recv() (*FindAllResponse, error)
}

type MetadataProcessingService_FindAllWithConditionsClient interface {
	Context() context.Context
	SendMsg(msg interface{}) error
	RecvMsg(msg interface{}) error
	Close() error
	Recv() (*FindAllResponse, error)
}

type MetadataProcessingService_FindAllWithTextSearchingClient interface {
	Context() context.Context
	SendMsg(msg interface{}) error
	RecvMsg(msg interface{}) error
	Close() error
	Recv() (*FindAllResponse, error)
}

type MetadataProcessingService_FindAllWithFullSearchingClient interface {
	Context() context.Context
	SendMsg(msg interface{}) error
	RecvMsg(msg interface{}) error
	Close() error
	Recv() (*FindAllResponse, error)
}

type MetadataProcessingServiceServer interface {
	GetFileMetadata(ctx context.Context, req *GetMetadataRequest, rsp *GetMetadataResponse) error
	UpdateFileMetadata(ctx context.Context, req *UpdateMetadataRequest, rsp *UpdateMetadataResponse) error
	FindAll(ctx context.Context, req *FindAllRequest, stream MetadataProcessingService_FindAllStream) error
	FindAllWithConditions(ctx context.Context, req *FindAllWithConditionsRequest, stream MetadataProcessingService_FindAllWithConditionsStream) error
	FindAllWithTextSearching(ctx context.Context, req *FindAllWithTextSearchingRequest, stream MetadataProcessingService_FindAllWithTextSearchingStream) error
	FindAllWithFullSearching(ctx context.Context, req *FindAllWithTextSearchingRequest, stream MetadataProcessingService_FindAllWithFullSearchingStream) error
	SaveFingerprint(ctx context.Context, req *SaveFingerprintRequest, rsp *SaveFingerprintResponse) error
	FindAllFingerprintsByID(ctx context.Context, req *FindAllFingerprintsByIDRequest, rsp *FindAllFingerprintsByIDResponse) error
}

type MetadataProcessingService_FindAllStream interface {
	Context() context.Context
	SendMsg(msg interface{}) error
	RecvMsg(msg interface{}) error
	Close() error
	Send(msg *FindAllResponse) error
}

type MetadataProcessingService_FindAllWithConditionsStream interface {
	Context() context.Context
	SendMsg(msg interface{}) error
	RecvMsg(msg interface{}) error
	Close() error
	Send(msg *FindAllResponse) error
}

type MetadataProcessingService_FindAllWithTextSearchingStream interface {
	Context() context.Context
	SendMsg(msg interface{}) error
	RecvMsg(msg interface{}) error
	Close() error
	Send(msg *FindAllResponse) error
}

type MetadataProcessingService_FindAllWithFullSearchingStream interface {
	Context() context.Context
	SendMsg(msg interface{}) error
	RecvMsg(msg interface{}) error
	Close() error
	Send(msg *FindAllResponse) error
}
